TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.35
  min_vel_x: 0.08

  max_vel_theta:  2.0
  min_vel_theta: -2.0
  min_in_place_vel_theta: 1.0

  acc_lim_x: 2.0
  acc_lim_y: 0.0
  acc_lim_theta: 0.6

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.10
  yaw_goal_tolerance: 0.05

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 3.5
  vx_samples: 18
  vtheta_samples: 20
  sim_granularity: 0.05


# TrajectoryPlannerROS:
#   holonimic_robot: false

#   min_vel_x: 0.08  #m/s
#   max_vel_x: 0.5 #m/s
  
#   min_vel_y: 0.0 #m/s
#   max_vel_y: 0.0 #m/s

#   max_vel_theta:  1.0
#   min_vel_theta: -1.0
#   min_in_place_vel_theta: 1.0

#   acc_lim_x: 1.0  #m/s^2 = (9.9 Nm/0.156 m)/(11kg/4)  
#   acc_lim_y: 0.0  #m/s^2
#   acc_lim_th: 1.0 #rad/s^2 22.2 rad/s^2 = acc_lim_x / radius = 3.6/0.162

# # Goal Tolerance Parameters
#   xy_goal_tolerance: 0.10
#   yaw_goal_tolerance: 0.05

# # Forward Simulation Parameters
#   sim_time: 0.8
#   vx_samples: 15
#   vtheta_samples: 20
#   sim_granularity: 0.05

#   meter_scoring: true