global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  
  static_map: true  
  update_frequency: 5.0 # Same as FPS of CNN obstacle map generator
  publish_frequency: 2.0
  transform_tolerance: 3.0

  # observation_sources: base_scan
  # base_scan: {data_type: LaserScan, topic: /scan,
  # marking: true, clearing: true, max_obstacle_height: 2.5, min_obstacle_height: 0.01}

