local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint

  update_frequency: 6.0
  publish_frequency: 3.0
  transform_tolerance: 1

  static_map: false  
  rolling_window: true # Costmap will remain centered around the robot.
  width: 6
  height: 6
  resolution: 0.05
  
