local_costmap:
  global_frame: UGV/odom
  robot_base_frame: base_footprint

  update_frequency: 5.0
  publish_frequency: 2.0
  transform_tolerance: 3

  static_map: false  
  rolling_window: true # Costmap will remain centered around the robot.
  width: 6
  height: 6
  resolution: 0.02
  inscribed_radius: 0.35
  circumscribed_radius: 0.4
  conservative_reset_dist: 1

  # observation_sources: base_scan
  # base_scan: {data_type: LaserScan, topic: /scan,
  # marking: true, clearing: true, max_obstacle_height: 1.0, min_obstacle_height: 0.08}
