teleop_twist_joy:
  axis_linear: 1
  scale_linear: 1
  scale_linear_turbo: 2
  axis_angular: 0
  scale_angular: -2
  scale_angular_turbo: -2
  enable_button: 8 #L2 trigger
  enable_turbo_button: 1 #Thumbstick button
